from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

from app import config

CSV_COLUMNS = [
    "source_id",
    "scheme_id",
    "title",
    "url",
    "source_type",
    "publisher",
    "authority",
    "extraction_method",
    "document_date",
    "retrieved_at",
    "http_status",
    "content_hash",
    "chunk_count",
    "fields_extracted",
    "is_complete",
]


def load_raw_index() -> dict[str, dict[str, Any]]:
    path = config.RAW_DIR / "index.json"
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def load_processed() -> dict[str, dict[str, Any]]:
    processed: dict[str, dict[str, Any]] = {}
    if not config.PROCESSED_DIR.is_dir():
        return processed
    for path in sorted(config.PROCESSED_DIR.glob("*.fields.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        source_id = payload.get("source_id") or path.name[: -len(".fields.json")]
        sections_path = path.with_name(f"{source_id}.sections.json")
        chunk_count = 0
        if sections_path.is_file():
            try:
                chunk_count = len(json.loads(sections_path.read_text(encoding="utf-8")))
            except json.JSONDecodeError:
                chunk_count = 0
        payload["section_count"] = chunk_count
        processed[source_id] = payload
    return processed


def load_chunk_counts() -> dict[str, int]:
    path = config.PROCESSED_DIR / "chunk_counts.json"
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def compute_chunk_counts() -> dict[str, int]:
    from app.ingest import chunk as chunk_mod
    from app.ingest import parse as parse_mod

    counts: dict[str, int] = {}
    for document in parse_mod.load_corpus():
        counts[document.source_id] = len(chunk_mod.get_chunker().split(document))
    path = config.PROCESSED_DIR / "chunk_counts.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(counts, indent=2, sort_keys=True), encoding="utf-8")
    return counts


def build_rows() -> list[dict[str, Any]]:
    raw_index = load_raw_index()
    processed = load_processed()
    chunk_counts = compute_chunk_counts()
    rows: list[dict[str, Any]] = []
    for source in config.SOURCES:
        source_id = source["source_id"]
        raw = raw_index.get(source_id, {})
        parsed = processed.get(source_id, {})
        fields = parsed.get("fields", {}) or {}
        rows.append(
            {
                "source_id": source_id,
                "scheme_id": source.get("scheme_id", ""),
                "title": source.get("title", ""),
                "url": source.get("url", ""),
                "source_type": source.get("source_type", ""),
                "publisher": source.get("publisher", ""),
                "authority": source.get("authority", ""),
                "extraction_method": parsed.get("extraction_method")
                or raw.get("extraction_method")
                or "",
                "document_date": parsed.get("document_date") or "",
                "retrieved_at": raw.get("retrieved_at") or "",
                "http_status": raw.get("http_status") if raw.get("http_status") else "",
                "content_hash": raw.get("content_hash") or "",
                "chunk_count": chunk_counts.get(source_id, 0),
                "fields_extracted": len(fields),
                "is_complete": parsed.get("is_complete", False),
            }
        )
    return rows


def write_csv(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(rows: list[dict[str, Any]], path: Path) -> None:
    lines: list[str] = [
        "# Source list",
        "",
        "Generated by `scripts/export_sources.py` from the actual contents of",
        "`data/processed/`, `data/raw/` and the vector store. Do not hand-edit.",
        "",
        "## In-scope scheme URLs (5)",
        "",
        "| # | Scheme | Plan | URL |",
        "| --- | --- | --- | --- |",
    ]
    for index, scheme in enumerate(config.SCHEMES, start=1):
        lines.append(f"| {index} | {scheme.name} | {scheme.plan} | {scheme.url} |")

    lines += ["", "## Ingested sources", ""]
    by_scheme: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        by_scheme.setdefault(row["scheme_id"], []).append(row)

    for scheme in config.SCHEMES:
        scheme_rows = by_scheme.get(scheme.scheme_id, [])
        lines += [
            f"### {scheme.scheme_id} — {scheme.name} ({scheme.plan})",
            "",
            "| source_id | authority | type | extraction | as of | fields | chunks | complete |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for row in scheme_rows:
            if row["is_complete"]:
                complete = "yes"
            elif row["fields_extracted"]:
                complete = "**NO — INCOMPLETE**"
            else:
                complete = "**NO — NOT FETCHED**"
            lines.append(
                f"| `{row['source_id']}` | {row['authority']} | {row['source_type']} | "
                f"{row['extraction_method'] or '—'} | {row['document_date'] or '—'} | "
                f"{row['fields_extracted']} | {row['chunk_count']} | {complete} |"
            )
        if not scheme_rows:
            lines.append("| — | — | — | — | — | 0 | 0 | **NO — NOT CONFIGURED** |")
        lines.append("")

    incomplete = [row for row in rows if not row["is_complete"]]
    lines += ["## Coverage gaps", ""]
    if incomplete:
        lines += [
            "The following sources are `is_complete=false` and are **excluded from the",
            "evaluation set** until resolved. An incomplete corpus must fail loudly,",
            "not silently under-answer.",
            "",
        ]
        for row in incomplete:
            reason = "not fetched" if not row["fields_extracted"] else "missing expected facts"
            lines.append(f"- `{row['source_id']}` ({row['authority']}, {row['source_type']}) — {reason}")
    else:
        lines.append("All configured sources parsed completely.")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = build_rows()
    config.ensure_dirs()
    write_csv(rows, config.DATA_DIR / "sources.csv")
    write_markdown(rows, config.DOCS_DIR / "sources.md")
    complete = sum(1 for row in rows if row["is_complete"])
    print(f"wrote data/sources.csv and docs/sources.md for {len(rows)} sources ({complete} complete)")


if __name__ == "__main__":
    main()
